/**
 * SYNC COPY FROM GOOGLE SHEETS
 *
 * This script fetches copy from a published Google Sheet
 * and generates the copy.ts file for the website.
 *
 * Usage: npm run sync-copy
 *
 * Setup:
 * 1. Create Google Sheet with columns: page, section, key, copy
 * 2. File → Share → Publish to web → CSV
 * 3. Paste the URL below
 */

const fs = require('fs');
const path = require('path');

// ============================================
// PASTE YOUR GOOGLE SHEET CSV URL HERE
// ============================================
const GOOGLE_SHEET_CSV_URL = process.env.GOOGLE_SHEET_URL || 'YOUR_GOOGLE_SHEET_CSV_URL_HERE';

// ============================================

async function fetchGoogleSheet() {
  console.log('📊 Fetching copy from Google Sheets...\n');

  if (GOOGLE_SHEET_CSV_URL === 'YOUR_GOOGLE_SHEET_CSV_URL_HERE') {
    console.error('❌ Error: Please set your Google Sheet URL in scripts/sync-copy.js');
    console.log('\nInstructions:');
    console.log('1. Open your Google Sheet');
    console.log('2. File → Share → Publish to web');
    console.log('3. Select "CSV" format');
    console.log('4. Copy the URL and paste it in this script\n');
    process.exit(1);
  }

  try {
    const response = await fetch(GOOGLE_SHEET_CSV_URL);
    const csvText = await response.text();
    return csvText;
  } catch (error) {
    console.error('❌ Error fetching Google Sheet:', error.message);
    process.exit(1);
  }
}

function parseCSV(csvText) {
  const lines = csvText.split('\n');
  const headers = lines[0].split(',').map(h => h.trim().toLowerCase());

  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim()) continue;

    // Handle CSV with quoted fields (commas inside quotes)
    const values = parseCSVLine(line);

    const row = {};
    headers.forEach((header, index) => {
      row[header] = values[index] || '';
    });
    rows.push(row);
  }

  return rows;
}

function parseCSVLine(line) {
  const values = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];

    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === ',' && !inQuotes) {
      values.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  values.push(current.trim());

  return values;
}

function buildCopyObject(rows) {
  const copy = {};

  for (const row of rows) {
    const { page, section, key, copy: text } = row;

    if (!page || !section || !key) continue;

    // Initialize nested objects
    if (!copy[page]) copy[page] = {};
    if (!copy[page][section]) copy[page][section] = {};

    // Handle array notation (e.g., "painPoints.0.title")
    if (key.includes('.')) {
      const parts = key.split('.');
      let current = copy[page][section];

      for (let i = 0; i < parts.length - 1; i++) {
        const part = parts[i];
        const nextPart = parts[i + 1];
        const isNextIndex = !isNaN(parseInt(nextPart));

        if (!current[part]) {
          current[part] = isNextIndex ? [] : {};
        }
        current = current[part];
      }

      const lastPart = parts[parts.length - 1];
      const parentPart = parts[parts.length - 2];

      if (!isNaN(parseInt(parentPart))) {
        // We're setting a property on an array item
        const index = parseInt(parentPart);
        if (!current[index]) current[index] = {};
        current[index][lastPart] = text;
      } else {
        current[lastPart] = text;
      }
    } else {
      copy[page][section][key] = text;
    }
  }

  return copy;
}

function generateTypeScript(copy) {
  const content = `/**
 * WEBSITE COPY - Auto-generated from Google Sheets
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edit the Google Sheet and run: npm run sync-copy
 *
 * Last synced: ${new Date().toISOString()}
 */

export const copy = ${JSON.stringify(copy, null, 2)} as const;

// Helper function to get nested copy
export function getCopy<T>(path: string, fallback?: T): T {
  const keys = path.split(".");
  let result: unknown = copy;

  for (const key of keys) {
    if (result && typeof result === "object" && key in result) {
      result = (result as Record<string, unknown>)[key];
    } else {
      return fallback as T;
    }
  }

  return result as T;
}
`;

  return content;
}

async function main() {
  // Fetch from Google Sheets
  const csvText = await fetchGoogleSheet();

  // Parse CSV
  const rows = parseCSV(csvText);
  console.log(`✅ Parsed ${rows.length} rows from Google Sheet\n`);

  // Build copy object
  const copy = buildCopyObject(rows);

  // Count pages and sections
  const pages = Object.keys(copy);
  const sections = pages.reduce((acc, page) => acc + Object.keys(copy[page]).length, 0);
  console.log(`📝 Found ${pages.length} pages, ${sections} sections\n`);

  // Generate TypeScript
  const tsContent = generateTypeScript(copy);

  // Write to file
  const outputPath = path.join(__dirname, '../src/lib/copy.ts');
  fs.writeFileSync(outputPath, tsContent);

  console.log('✅ Successfully synced copy to src/lib/copy.ts\n');
  console.log('🚀 Restart your dev server to see changes\n');
}

main();
